// Policies data scraped from Boardable - Foothill-De Anza Community College District
// Source: https://site.boardable.com/foothill-de-anza-community-college-district/policies/2ba933-board-policy
// Type is auto-detected from number prefix: "BP" = Board Policy, "AP" = Administrative Procedure.
// You can also set type explicitly per entry. Status defaults to "needs-review" and is managed in localStorage.

var POLICIES_DATA = [
// Chapter 1 - The District
{number:"BP 1100",title:"The Foothill-De Anza Community College District Name",chapter:"Chapter 1 - The District",adopted:"06/17/2013",lastRevised:"07/08/2024"},
{number:"BP 1140",title:"Community Service",chapter:"Chapter 1 - The District",adopted:"11/30/-0001",lastRevised:"11/15/1993"},
{number:"BP 1150",title:"Community Services Short Courses and Fee-Based Programs",chapter:"Chapter 1 - The District",adopted:"11/30/-0001",lastRevised:"11/15/1993"},
{number:"BP 1200",title:"Mission of the Foothill-De Anza Community College District",chapter:"Chapter 1 - The District",adopted:"07/12/2004",lastRevised:"07/08/2024"},
{number:"BP 1800",title:"Auxiliary Organizations",chapter:"Chapter 1 - The District",adopted:"06/03/1996",lastRevised:""},
// Chapter 2 - Board of Trustees
{number:"BP 2010",title:"Board Membership",chapter:"Chapter 2 - Board of Trustees",adopted:"11/30/-0001",lastRevised:"01/13/2025"},
{number:"BP 2015",title:"Student Members",chapter:"Chapter 2 - Board of Trustees",adopted:"05/03/1982",lastRevised:"12/08/2025"},
{number:"BP 2100",title:"Board Elections",chapter:"Chapter 2 - Board of Trustees",adopted:"06/03/2013",lastRevised:"01/13/2025"},
{number:"BP 2110",title:"Vacancies on the Board",chapter:"Chapter 2 - Board of Trustees",adopted:"11/30/-0001",lastRevised:"01/13/2025"},
{number:"BP 2200",title:"Board Philosophy, Mission, and Roles and Responsibilities",chapter:"Chapter 2 - Board of Trustees",adopted:"02/03/2014",lastRevised:""},
{number:"BP 2210",title:"Officers of the Board",chapter:"Chapter 2 - Board of Trustees",adopted:"11/30/-0001",lastRevised:"01/13/2025"},
{number:"BP 2220",title:"Committees of the Board",chapter:"Chapter 2 - Board of Trustees",adopted:"11/30/-0001",lastRevised:"01/13/2025"},
{number:"BP 2222",title:"Student Role in Governance",chapter:"Chapter 2 - Board of Trustees",adopted:"02/08/1993",lastRevised:""},
{number:"BP 2223",title:"Role of the Academic Senate in Academic and Professional Matters",chapter:"Chapter 2 - Board of Trustees",adopted:"06/07/1993",lastRevised:"05/01/1995"},
{number:"BP 2224",title:"Role of Classified Staff in Governance",chapter:"Chapter 2 - Board of Trustees",adopted:"07/19/1999",lastRevised:""},
{number:"BP 2305",title:"Annual Organizational Meeting",chapter:"Chapter 2 - Board of Trustees",adopted:"02/03/1997",lastRevised:"12/08/2025"},
{number:"BP 2310",title:"Regular Meetings of the Board",chapter:"Chapter 2 - Board of Trustees",adopted:"02/03/1997",lastRevised:"01/13/2025"},
{number:"BP 2315",title:"Closed Session",chapter:"Chapter 2 - Board of Trustees",adopted:"02/07/2011",lastRevised:"12/08/2025"},
{number:"BP 2320",title:"Special and Emergency Meetings",chapter:"Chapter 2 - Board of Trustees",adopted:"02/07/2011",lastRevised:"01/13/2025"},
{number:"BP 2330",title:"Quorum and Voting",chapter:"Chapter 2 - Board of Trustees",adopted:"12/09/2013",lastRevised:"01/13/2025"},
{number:"BP 2340",title:"Board Meeting Agendas",chapter:"Chapter 2 - Board of Trustees",adopted:"02/03/1997",lastRevised:"12/08/2025"},
{number:"BP 2345",title:"Public Participation at Board Meetings",chapter:"Chapter 2 - Board of Trustees",adopted:"11/30/-0001",lastRevised:"01/13/2014"},
{number:"BP 2350",title:"Speakers at Board Meetings",chapter:"Chapter 2 - Board of Trustees",adopted:"01/13/2014",lastRevised:"12/04/2017"},
{number:"BP 2355",title:"Decorum at Board Meetings",chapter:"Chapter 2 - Board of Trustees",adopted:"02/03/2014",lastRevised:""},
{number:"BP 2360",title:"Minutes",chapter:"Chapter 2 - Board of Trustees",adopted:"03/03/2014",lastRevised:""},
{number:"BP 2365",title:"Recording",chapter:"Chapter 2 - Board of Trustees",adopted:"03/03/2014",lastRevised:""},
{number:"BP 2410",title:"Policy and Administrative Procedure",chapter:"Chapter 2 - Board of Trustees",adopted:"05/01/1995",lastRevised:"07/08/2024"},
{number:"BP 2430",title:"Delegation of Authority to Chancellor",chapter:"Chapter 2 - Board of Trustees",adopted:"11/30/-0001",lastRevised:"08/04/2025"},
{number:"BP 2431",title:"Chancellor or President Selection",chapter:"Chapter 2 - Board of Trustees",adopted:"02/07/2011",lastRevised:"08/04/2025"},
{number:"BP 2432",title:"Acting Chancellor in Absence of Chancellor",chapter:"Chapter 2 - Board of Trustees",adopted:"11/30/-0001",lastRevised:"06/12/2017"},
{number:"BP 2433",title:"Acting College President in Absence of a President",chapter:"Chapter 2 - Board of Trustees",adopted:"11/30/-0001",lastRevised:"08/04/2025"},
{number:"BP 2435",title:"Evaluation of Chancellor",chapter:"Chapter 2 - Board of Trustees",adopted:"06/21/2004",lastRevised:"05/15/2014"},
{number:"BP 2550",title:"Staff Advisory Functions",chapter:"Chapter 2 - Board of Trustees",adopted:"11/30/-0001",lastRevised:"08/04/2025"},
{number:"BP 2560",title:"Relation of Board to Management Personnel",chapter:"Chapter 2 - Board of Trustees",adopted:"06/20/1977",lastRevised:"08/04/2025"},
{number:"BP 2600.1",title:"Compensation of Management Personnel",chapter:"Chapter 2 - Board of Trustees",adopted:"06/20/1977",lastRevised:"05/01/1995"},
{number:"BP 2615",title:"Board Representatives for Meet and Confer or Meet and Negotiate Process",chapter:"Chapter 2 - Board of Trustees",adopted:"11/30/-0001",lastRevised:"08/04/2025"},
{number:"BP 2710",title:"Conflict of Interest",chapter:"Chapter 2 - Board of Trustees",adopted:"11/03/2014",lastRevised:""},
{number:"BP 2712",title:"Conflict of Interest Code",chapter:"Chapter 2 - Board of Trustees",adopted:"02/18/2003",lastRevised:"10/03/2022"},
{number:"BP 2715",title:"Code of Ethics/Standards of Practice",chapter:"Chapter 2 - Board of Trustees",adopted:"05/05/1992",lastRevised:"08/04/2025"},
{number:"BP 2716",title:"Political Activity",chapter:"Chapter 2 - Board of Trustees",adopted:"06/16/2014",lastRevised:""},
{number:"BP 2717",title:"Personal Use of District Resources",chapter:"Chapter 2 - Board of Trustees",adopted:"06/16/2014",lastRevised:""},
{number:"BP 2720",title:"Communications among Board Members",chapter:"Chapter 2 - Board of Trustees",adopted:"07/07/2014",lastRevised:""},
{number:"BP 2725",title:"Board Member Compensation",chapter:"Chapter 2 - Board of Trustees",adopted:"01/08/2001",lastRevised:"07/07/2014"},
{number:"BP 2730",title:"Board Member Health Benefits",chapter:"Chapter 2 - Board of Trustees",adopted:"02/01/1982",lastRevised:"05/05/2014"},
{number:"BP 2735",title:"Board of Trustees Travel",chapter:"Chapter 2 - Board of Trustees",adopted:"03/01/2010",lastRevised:"07/03/2017"},
{number:"BP 2740",title:"Board Education",chapter:"Chapter 2 - Board of Trustees",adopted:"",lastRevised:""},
{number:"BP 2745",title:"Board Self-Evaluation",chapter:"Chapter 2 - Board of Trustees",adopted:"06/21/2004",lastRevised:"08/04/2025"},
{number:"BP 2750",title:"Board Member Absence from the State",chapter:"Chapter 2 - Board of Trustees",adopted:"08/04/2014",lastRevised:""},
{number:"BP 2800",title:"Campaign Assistance to Board Candidates",chapter:"Chapter 2 - Board of Trustees",adopted:"11/30/-0001",lastRevised:"08/04/2025"},
// Chapter 3 - General Institution
{number:"BP 3100",title:"Organizational Structure",chapter:"Chapter 3 - General Institution",adopted:"11/30/-0001",lastRevised:"12/08/2014"},
{number:"BP 3121",title:"Standards of Ethical Conduct",chapter:"Chapter 3 - General Institution",adopted:"06/20/2011",lastRevised:""},
{number:"BP 3122",title:"Acceptance of Gifts",chapter:"Chapter 3 - General Institution",adopted:"11/30/-0001",lastRevised:"12/15/2003"},
{number:"BP 3200",title:"Accreditation",chapter:"Chapter 3 - General Institution",adopted:"11/30/-0001",lastRevised:"04/06/2026"},
{number:"BP 3217",title:"Non-Smoking Areas",chapter:"Chapter 3 - General Institution",adopted:"01/08/1996",lastRevised:"03/12/2012"},
{number:"BP 3225",title:"Institutional Effectiveness",chapter:"Chapter 3 - General Institution",adopted:"07/13/2015",lastRevised:"04/06/2026"},
{number:"BP 3250",title:"Computer and Network Use: Rights and Responsibilities",chapter:"Chapter 3 - General Institution",adopted:"11/17/1997",lastRevised:"12/05/2005"},
{number:"BP 3250 (New)",title:"Institutional Planning",chapter:"Chapter 3 - General Institution",adopted:"07/12/2004",lastRevised:"04/06/2026"},
{number:"BP 3260",title:"Electronic Information Security",chapter:"Chapter 3 - General Institution",adopted:"01/20/2009",lastRevised:""},
{number:"BP 3280",title:"Grants",chapter:"Chapter 3 - General Institution",adopted:"11/30/-0001",lastRevised:"12/08/2014"},
{number:"BP 3300",title:"Public Records",chapter:"Chapter 3 - General Institution",adopted:"",lastRevised:""},
{number:"BP 3320",title:"Police Department",chapter:"Chapter 3 - General Institution",adopted:"",lastRevised:""},
{number:"BP 3410 (New)",title:"Nondiscrimination",chapter:"Chapter 3 - General Institution",adopted:"11/15/1993",lastRevised:"07/12/2021"},
{number:"BP 3410",title:"Classification, Retention and Destruction of Records",chapter:"Chapter 3 - General Institution",adopted:"",lastRevised:""},
{number:"BP 3430",title:"Prohibition of Harassment",chapter:"Chapter 3 - General Institution",adopted:"02/03/2025",lastRevised:""},
{number:"BP 3433",title:"Prohibition of Sexual Harassment under Title IX",chapter:"Chapter 3 - General Institution",adopted:"09/08/2025",lastRevised:""},
{number:"BP 3440",title:"Service Animals",chapter:"Chapter 3 - General Institution",adopted:"03/11/2013",lastRevised:""},
{number:"BP 3441",title:"Animals on Campus",chapter:"Chapter 3 - General Institution",adopted:"",lastRevised:""},
{number:"BP 3500",title:"Alcohol on Campus",chapter:"Chapter 3 - General Institution",adopted:"03/11/2013",lastRevised:""},
{number:"BP 3510",title:"Violence in the Workplace",chapter:"Chapter 3 - General Institution",adopted:"10/21/1996",lastRevised:"01/11/2021"},
{number:"BP 3518",title:"Child Abuse Reporting",chapter:"Chapter 3 - General Institution",adopted:"05/04/2020",lastRevised:""},
{number:"BP 3530",title:"Weapons on Campus",chapter:"Chapter 3 - General Institution",adopted:"12/08/2014",lastRevised:""},
{number:"BP 3540",title:"Sexual and Other Assaults on Campus and in Campus Programs",chapter:"Chapter 3 - General Institution",adopted:"09/08/2025",lastRevised:"09/08/2025"},
{number:"BP 3600",title:"Whistleblower Protection",chapter:"Chapter 3 - General Institution",adopted:"06/07/2010",lastRevised:""},
{number:"BP 3810",title:"Claims Against the District",chapter:"Chapter 3 - General Institution",adopted:"06/10/2019",lastRevised:""},
{number:"BP 3900",title:"Speech: Time, Place, and Manner",chapter:"Chapter 3 - General Institution",adopted:"01/04/1999",lastRevised:"05/03/2021"},
// Chapter 4 - Academic Affairs
{number:"BP 4010",title:"Academic Calendar",chapter:"Chapter 4 - Academic Affairs",adopted:"01/12/2026",lastRevised:""},
{number:"BP 4020",title:"Program, Curriculum, and Course Development",chapter:"Chapter 4 - Academic Affairs",adopted:"11/30/-0001",lastRevised:"03/09/2026"},
{number:"BP 4021",title:"Program Discontinuance",chapter:"Chapter 4 - Academic Affairs",adopted:"",lastRevised:""},
{number:"BP 4025",title:"Philosophy and Criteria for Degrees and General Education",chapter:"Chapter 4 - Academic Affairs",adopted:"11/30/-0001",lastRevised:"03/09/2026"},
{number:"BP 4050",title:"Articulation",chapter:"Chapter 4 - Academic Affairs",adopted:"04/07/2008",lastRevised:"06/08/2026"},
{number:"BP 4070",title:"Course Auditing and Auditing Fees",chapter:"Chapter 4 - Academic Affairs",adopted:"07/12/2004",lastRevised:"06/08/2026"},
{number:"BP 4100 (New)",title:"Graduation Requirements for Degrees and Certificates",chapter:"Chapter 4 - Academic Affairs",adopted:"11/30/-0001",lastRevised:"03/09/2026"},
{number:"BP 4220",title:"Standards of Scholarship",chapter:"Chapter 4 - Academic Affairs",adopted:"04/06/2026",lastRevised:""},
{number:"BP 4225",title:"Course Repetition to Alleviate a Grade for Substandard Academic Work",chapter:"Chapter 4 - Academic Affairs",adopted:"06/16/2008",lastRevised:"09/08/2014"},
{number:"BP 4226",title:"Multiple and Overlapping Enrollments",chapter:"Chapter 4 - Academic Affairs",adopted:"04/06/2026",lastRevised:""},
{number:"BP 4230",title:"Grading",chapter:"Chapter 4 - Academic Affairs",adopted:"01/19/1981",lastRevised:"06/10/2019"},
{number:"BP 4235",title:"Credit for Prior Learning",chapter:"Chapter 4 - Academic Affairs",adopted:"11/30/-0001",lastRevised:"12/14/2020"},
{number:"BP 4237",title:"Honors Courses and Programs",chapter:"Chapter 4 - Academic Affairs",adopted:"11/30/-0001",lastRevised:"04/06/2026"},
{number:"BP 4240",title:"Academic Renewal",chapter:"Chapter 4 - Academic Affairs",adopted:"01/04/1999",lastRevised:"04/03/2017"},
{number:"BP 6040",title:"Teaching of Religion",chapter:"Chapter 4 - Academic Affairs",adopted:"08/16/1976",lastRevised:"03/02/1998"},
{number:"BP 6060",title:"Prerequisites/Corequisites",chapter:"Chapter 4 - Academic Affairs",adopted:"06/06/1994",lastRevised:"03/11/2013"},
{number:"BP 6140",title:"Textbooks and Manuals",chapter:"Chapter 4 - Academic Affairs",adopted:"11/30/-0001",lastRevised:"03/02/1998"},
{number:"BP 6150",title:"Supplementary Class Activities",chapter:"Chapter 4 - Academic Affairs",adopted:"11/30/-0001",lastRevised:"03/02/1998"},
{number:"BP 6160",title:"Speakers",chapter:"Chapter 4 - Academic Affairs",adopted:"11/30/-0001",lastRevised:"03/02/1998"},
{number:"BP 6170",title:"Library Materials Selection",chapter:"Chapter 4 - Academic Affairs",adopted:"11/30/-0001",lastRevised:"03/02/1998"},
// Chapter 5 - Student Services
{number:"BP 5005",title:"Residency Requirements",chapter:"Chapter 5 - Student Services",adopted:"",lastRevised:""},
{number:"BP 5010",title:"Admissions and Concurrent Enrollment",chapter:"Chapter 5 - Student Services",adopted:"01/04/1999",lastRevised:"05/11/2026"},
{number:"BP 5012",title:"International Students",chapter:"Chapter 5 - Student Services",adopted:"01/04/1999",lastRevised:"05/11/2026"},
{number:"BP 5020",title:"Nonresident Tuition",chapter:"Chapter 5 - Student Services",adopted:"01/04/1999",lastRevised:"05/06/2019"},
{number:"BP 5025",title:"Student Contributions",chapter:"Chapter 5 - Student Services",adopted:"05/03/1982",lastRevised:""},
{number:"BP 5030",title:"Student Fees",chapter:"Chapter 5 - Student Services",adopted:"01/04/1999",lastRevised:"06/08/2026"},
{number:"BP 5031",title:"Instructional Materials",chapter:"Chapter 5 - Student Services",adopted:"11/30/-0001",lastRevised:"06/08/2026"},
{number:"BP 5035",title:"Withholding Student Diplomas and Registration",chapter:"Chapter 5 - Student Services",adopted:"",lastRevised:""},
{number:"BP 5050",title:"Disclosure of Student Records",chapter:"Chapter 5 - Student Services",adopted:"11/30/-0001",lastRevised:"03/11/2013"},
{number:"BP 5050 (New)",title:"Student Success and Support Program",chapter:"Chapter 5 - Student Services",adopted:"01/04/1999",lastRevised:"05/11/2026"},
{number:"BP 5055",title:"Contacting Students",chapter:"Chapter 5 - Student Services",adopted:"11/30/-0001",lastRevised:""},
{number:"BP 5055 (New)",title:"Enrollment Priorities",chapter:"Chapter 5 - Student Services",adopted:"06/16/2008",lastRevised:"12/08/2025"},
{number:"BP 5075",title:"Disabled Students/Special Education Program",chapter:"Chapter 5 - Student Services",adopted:"",lastRevised:""},
{number:"BP 5075 (New)",title:"Credit Course Drops and Withdrawals",chapter:"Chapter 5 - Student Services",adopted:"06/04/2012",lastRevised:"07/07/2014"},
{number:"BP 5076",title:"Suspension/Termination of Support Services for Students with Disabilities",chapter:"Chapter 5 - Student Services",adopted:"12/06/2004",lastRevised:""},
{number:"BP 5077",title:"Academic Accommodations for Students with Disabilities",chapter:"Chapter 5 - Student Services",adopted:"12/06/2004",lastRevised:""},
{number:"BP 5078",title:"Course Repeatability for Students with Disabilities",chapter:"Chapter 5 - Student Services",adopted:"12/06/2004",lastRevised:""},
{number:"BP 5085",title:"Extended Opportunity Programs and Services",chapter:"Chapter 5 - Student Services",adopted:"01/04/1999",lastRevised:""},
{number:"BP 5090",title:"Health Services",chapter:"Chapter 5 - Student Services",adopted:"06/03/1996",lastRevised:"08/27/2007"},
{number:"BP 5095",title:"Infectious Disease Control",chapter:"Chapter 5 - Student Services",adopted:"01/06/1987",lastRevised:"01/04/1999"},
{number:"BP 5110",title:"Counseling",chapter:"Chapter 5 - Student Services",adopted:"01/04/1999",lastRevised:"08/05/2024"},
{number:"BP 5120",title:"Transfer Center",chapter:"Chapter 5 - Student Services",adopted:"06/08/2026",lastRevised:""},
{number:"BP 5130",title:"Financial Aid",chapter:"Chapter 5 - Student Services",adopted:"01/04/1999",lastRevised:"03/09/2026"},
{number:"BP 5300",title:"Student Equity",chapter:"Chapter 5 - Student Services",adopted:"06/16/2008",lastRevised:"06/12/2017"},
{number:"BP 5500",title:"Student Rights and Responsibilities",chapter:"Chapter 5 - Student Services",adopted:"01/04/1999",lastRevised:""},
{number:"BP 5560",title:"Associated Students Organization",chapter:"Chapter 5 - Student Services",adopted:"11/30/-0001",lastRevised:"07/06/2009"},
{number:"BP 5561",title:"Associated Students Elections",chapter:"Chapter 5 - Student Services",adopted:"06/15/2009",lastRevised:""},
{number:"BP 5562",title:"Associated Students Finance",chapter:"Chapter 5 - Student Services",adopted:"01/04/1999",lastRevised:"06/15/2009"},
{number:"BP 5570",title:"Campus Center Operations",chapter:"Chapter 5 - Student Services",adopted:"11/30/-0001",lastRevised:"03/07/1988"},
{number:"BP 5575",title:"Use of Campus Center Income",chapter:"Chapter 5 - Student Services",adopted:"01/04/1999",lastRevised:""},
{number:"BP 5580",title:"Bookstore",chapter:"Chapter 5 - Student Services",adopted:"11/30/-0001",lastRevised:"01/04/1999"},
{number:"BP 5700",title:"Intercollegiate Athletics",chapter:"Chapter 5 - Student Services",adopted:"04/02/2018",lastRevised:""},
// Chapter 6 - Business and Fiscal Affairs
{number:"BP 3130",title:"Investment of District Funds",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"11/30/-0001",lastRevised:"08/16/1999"},
{number:"BP 3140",title:"Purchasing Policy",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"08/16/1999",lastRevised:""},
{number:"BP 3142",title:"Inventory Control",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"11/30/-0001",lastRevised:"08/16/1999"},
{number:"BP 3143",title:"Contracts",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"08/16/1999",lastRevised:"12/13/2004"},
{number:"BP 3151",title:"Attendance Accounting",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"03/15/1982",lastRevised:"08/16/1999"},
{number:"BP 3152.5",title:"Travel Tour Solicitation",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"11/30/-0001",lastRevised:"08/16/1999"},
{number:"BP 3200",title:"Facilities Philosophy and Priorities Statement",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"11/19/1990",lastRevised:"08/16/1999"},
{number:"BP 3205",title:"Community Use of District Facilities",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"11/30/-0001",lastRevised:"08/16/1999"},
{number:"BP 3213",title:"Control of Major Construction Project Costs/Approval of Construction Change Orders",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"11/30/-0001",lastRevised:"08/27/2007"},
{number:"BP 3216",title:"Naming of College and District Buildings or Facilities",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"02/21/1980",lastRevised:"08/27/2001"},
{number:"BP 3225",title:"Access Control Policy",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"06/16/2008",lastRevised:"08/27/2012"},
{number:"BP 3310",title:"Risk Management",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"11/30/-0001",lastRevised:"08/16/1999"},
{number:"BP 3311",title:"Extension of District Insurance Protection",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"09/21/1981",lastRevised:"08/16/1999"},
{number:"BP 3312",title:"Injury/Illness Prevention",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"08/16/1999",lastRevised:""},
{number:"BP 3314",title:"Board Member/Employee Indemnification",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"08/16/1999",lastRevised:""},
{number:"BP 3315",title:"Emergency Response Plan",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"03/07/2011",lastRevised:""},
{number:"BP 3321",title:"Local Law Enforcement",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"07/12/2004",lastRevised:""},
{number:"BP 6100",title:"Delegation of Authority, Business and Fiscal Affairs",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"08/16/1999",lastRevised:"03/09/2026"},
{number:"BP 6150",title:"Designation of Authorized Signatures",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"08/16/1999",lastRevised:"03/09/2026"},
{number:"BP 6200",title:"Budget Preparation",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"11/30/-0001",lastRevised:"03/09/2026"},
{number:"BP 6250",title:"Budget Management",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"11/30/-0001",lastRevised:"04/06/2026"},
{number:"BP 6300",title:"Fiscal Management",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"08/16/1999",lastRevised:"03/09/2026"},
{number:"BP 6307",title:"Debt Issuance and Management",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"03/15/2021",lastRevised:""},
{number:"BP 6310",title:"Accounting",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"11/30/-0001",lastRevised:"03/09/2026"},
{number:"BP 6322",title:"Employee Indemnity Bonds",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"08/16/1999",lastRevised:"03/09/2026"},
{number:"BP 6400",title:"Financial Audits",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"11/30/-0001",lastRevised:"03/09/2026"},
{number:"BP 6401",title:"Audit and Finance Committee",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"04/20/1992",lastRevised:"03/09/2026"},
{number:"BP 6450",title:"Wireless or Cellular Telephone Use",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"09/11/2023",lastRevised:""},
{number:"BP 6530",title:"District Vehicles",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"08/16/1999",lastRevised:"03/09/2026"},
{number:"BP 6535",title:"Use of District Equipment",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"11/30/-0001",lastRevised:"03/09/2026"},
{number:"BP 6550",title:"Disposal of Property",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"11/30/-0001",lastRevised:"03/09/2026"},
{number:"BP 6601",title:"Neighborhood Outreach",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"07/12/2004",lastRevised:""},
{number:"BP 6740",title:"Citizens' Bond Oversight Committee",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"02/03/2014",lastRevised:""},
{number:"BP 6750",title:"Parking",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"",lastRevised:""},
{number:"BP 6870",title:"Police Department",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"07/12/2004",lastRevised:"05/01/2023"},
{number:"BP 6910",title:"Housing",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"09/08/2025",lastRevised:""},
{number:"BP 6960",title:"Environmentally Sustainable Practices",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"08/16/1999",lastRevised:"03/09/2026"},
{number:"BP 6970",title:"Art Objects in Campus Buildings and on Campus Grounds",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"03/26/1990",lastRevised:"03/09/2026"},
{number:"BP 6980",title:"Signage on District Property",chapter:"Chapter 6 - Business and Fiscal Affairs",adopted:"03/18/1993",lastRevised:"03/09/2026"},
// Chapter 7 - Human Resources
{number:"BP 4100",title:"Cultural Diversity/Equal Opportunity",chapter:"Chapter 7 - Human Resources",adopted:"11/30/-0001",lastRevised:"04/01/2002"},
{number:"BP 4115",title:"Nepotism",chapter:"Chapter 7 - Human Resources",adopted:"05/20/1996",lastRevised:""},
{number:"BP 4120",title:"Employment in Specially Funded Programs",chapter:"Chapter 7 - Human Resources",adopted:"11/21/1977",lastRevised:""},
{number:"BP 4125",title:"Authorization to Offer Employment",chapter:"Chapter 7 - Human Resources",adopted:"11/30/-0001",lastRevised:"12/06/2010"},
{number:"BP 4130",title:"Employment",chapter:"Chapter 7 - Human Resources",adopted:"11/18/1996",lastRevised:"11/04/2002"},
{number:"BP 4135",title:"Faculty Hiring Qualifications",chapter:"Chapter 7 - Human Resources",adopted:"11/18/1996",lastRevised:"04/01/2002"},
{number:"BP 4145",title:"Board Advised of Evaluations",chapter:"Chapter 7 - Human Resources",adopted:"11/30/-0001",lastRevised:"09/08/2003"},
{number:"BP 4150",title:"Personnel Files",chapter:"Chapter 7 - Human Resources",adopted:"11/30/-0001",lastRevised:"11/18/1996"},
{number:"BP 4157",title:"Release Time",chapter:"Chapter 7 - Human Resources",adopted:"07/14/1997",lastRevised:""},
{number:"BP 4160",title:"Professional Activities",chapter:"Chapter 7 - Human Resources",adopted:"11/30/-0001",lastRevised:"11/18/1996"},
{number:"BP 4180",title:"Research and Publications by Staff",chapter:"Chapter 7 - Human Resources",adopted:"11/30/-0001",lastRevised:""},
{number:"BP 4185",title:"Publication of Instructional Materials",chapter:"Chapter 7 - Human Resources",adopted:"",lastRevised:""},
{number:"BP 4190",title:"Academic Freedom",chapter:"Chapter 7 - Human Resources",adopted:"11/30/-0001",lastRevised:"01/05/2010"},
{number:"BP 4195",title:"Political Campaigning by Faculty Members",chapter:"Chapter 7 - Human Resources",adopted:"11/30/-0001",lastRevised:"04/04/2011"},
{number:"BP 4200",title:"Compensation",chapter:"Chapter 7 - Human Resources",adopted:"11/18/1996",lastRevised:"10/06/2003"},
{number:"BP 4205",title:"Family Medical Leave Act",chapter:"Chapter 7 - Human Resources",adopted:"09/11/1995",lastRevised:"04/01/2002"},
{number:"BP 4300",title:"Dismissal for Cause",chapter:"Chapter 7 - Human Resources",adopted:"01/17/1977",lastRevised:"11/18/1996"},
{number:"BP 4500",title:"Drug-Free Workplace",chapter:"Chapter 7 - Human Resources",adopted:"01/22/1990",lastRevised:""},
{number:"BP 4505",title:"Drug Testing",chapter:"Chapter 7 - Human Resources",adopted:"06/17/1996",lastRevised:""},
{number:"BP 4515",title:"Prevention of Workplace Violence",chapter:"Chapter 7 - Human Resources",adopted:"",lastRevised:""},
{number:"BP 4670",title:"Requesting and Receiving Accommodation(s) Under the Americans with Disabilities Act",chapter:"Chapter 7 - Human Resources",adopted:"04/04/1994",lastRevised:"07/25/1994"},
{number:"BP 7210",title:"Academic Employees",chapter:"Chapter 7 - Human Resources",adopted:"11/30/-0001",lastRevised:"08/01/2022"},
{number:"BP 7211",title:"Equivalency",chapter:"Chapter 7 - Human Resources",adopted:"04/01/1996",lastRevised:"07/13/2020"},
{number:"BP 7330",title:"Communicable Disease - Employees",chapter:"Chapter 7 - Human Resources",adopted:"11/30/-0001",lastRevised:"07/12/2021"},
{number:"BP 7337",title:"Fingerprinting of Employees, Volunteers and Student Workers",chapter:"Chapter 7 - Human Resources",adopted:"06/11/1990",lastRevised:"03/03/2014"},
{number:"BP 7400",title:"Employee Travel",chapter:"Chapter 7 - Human Resources",adopted:"11/30/-0001",lastRevised:"02/05/2018"},
// Administrative Procedures (AP)
{number:"AP 2105",title:"Student Trustee Selection Procedures",chapter:"Chapter 2 - Board of Trustees",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 2110",title:"Vacancies on the Board",chapter:"Chapter 2 - Board of Trustees",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 2320",title:"Special and Emergency Meetings",chapter:"Chapter 2 - Board of Trustees",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 2325",title:"Teleconferenced Meetings",chapter:"Chapter 2 - Board of Trustees",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 2340",title:"Board Meeting Agendas",chapter:"Chapter 2 - Board of Trustees",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 2365",title:"Recording",chapter:"Chapter 2 - Board of Trustees",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 2410",title:"Board Policies and Administrative Procedures",chapter:"Chapter 2 - Board of Trustees",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 2430",title:"Delegation of Authority to the Chancellor",chapter:"Chapter 2 - Board of Trustees",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 2435",title:"Evaluation of Chancellor",chapter:"Chapter 2 - Board of Trustees",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 2710",title:"Conflict of Interest",chapter:"Chapter 2 - Board of Trustees",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 2714",title:"Distribution of Tickets or Passes",chapter:"Chapter 2 - Board of Trustees",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 3100",title:"Organizational Structure",chapter:"Chapter 3 - General Institution",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 3122",title:"Acceptance of Gifts",chapter:"Chapter 3 - General Institution",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 3200",title:"Accreditation",chapter:"Chapter 3 - General Institution",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 3217",title:"Non-Smoking Areas",chapter:"Chapter 3 - General Institution",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 3225",title:"Institutional Effectiveness",chapter:"Chapter 3 - General Institution",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 3250",title:"Procedures Regarding Misuse of Computer Information",chapter:"Chapter 3 - General Institution",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 3250 (New)",title:"Institutional Planning",chapter:"Chapter 3 - General Institution",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 3260",title:"Electronic Information Security",chapter:"Chapter 3 - General Institution",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 3280",title:"Grants",chapter:"Chapter 3 - General Institution",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 3300",title:"Public Records",chapter:"Chapter 3 - General Institution",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 3410 (New)",title:"Nondiscrimination",chapter:"Chapter 3 - General Institution",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 3415",title:"Immigration Enforcement Activities",chapter:"Chapter 3 - General Institution",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 3430",title:"Prohibition of Harassment",chapter:"Chapter 3 - General Institution",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 3433",title:"Prohibition of Sexual Harassment under Title IX",chapter:"Chapter 3 - General Institution",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 3434",title:"Responding to Harassment Based on Sex under Title IX",chapter:"Chapter 3 - General Institution",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 3435",title:"Discrimination and Harassment Complaints and Investigations",chapter:"Chapter 3 - General Institution",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 3440",title:"Service Animals",chapter:"Chapter 3 - General Institution",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 3507",title:"COVID-19 Vaccination Requirement",chapter:"Chapter 3 - General Institution",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 3510",title:"Violence in the Workplace",chapter:"Chapter 3 - General Institution",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 3518",title:"Child Abuse Reporting",chapter:"Chapter 3 - General Institution",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 3530",title:"Weapons on Campus",chapter:"Chapter 3 - General Institution",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 3540",title:"Sexual and Other Assaults on Campus",chapter:"Chapter 3 - General Institution",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 3560",title:"Alcoholic Beverages",chapter:"Chapter 3 - General Institution",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 3600",title:"Whistleblower Protection",chapter:"Chapter 3 - General Institution",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 3810",title:"Claims Against the District",chapter:"Chapter 3 - General Institution",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 3900",title:"Speech: Time, Place, and Manner",chapter:"Chapter 3 - General Institution",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 3910",title:"Autonomous Aircraft Systems (AAS)",chapter:"Chapter 3 - General Institution",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 4010",title:"Academic Calendar",chapter:"Chapter 4 - Academic Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 4020",title:"Program and Curriculum Development",chapter:"Chapter 4 - Academic Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 4021",title:"Program Discontinuance",chapter:"Chapter 4 - Academic Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 4022",title:"Course Approval",chapter:"Chapter 4 - Academic Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 4025",title:"Philosophy and Criteria for Bachelor Degree, Associate Degree and General Education",chapter:"Chapter 4 - Academic Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 4050",title:"Articulation",chapter:"Chapter 4 - Academic Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 4070",title:"Course Auditing and Auditing Fees",chapter:"Chapter 4 - Academic Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 4100",title:"Graduation Requirements for Degrees and Certificates",chapter:"Chapter 4 - Academic Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 4105",title:"Distance Education and Correspondence Education",chapter:"Chapter 4 - Academic Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 4220",title:"Standards of Scholarship - Delegation",chapter:"Chapter 4 - Academic Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 4225",title:"Course Repetition",chapter:"Chapter 4 - Academic Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 4226",title:"Multiple and Overlapping Enrollment",chapter:"Chapter 4 - Academic Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 4230",title:"Grading and Academic Record Symbols",chapter:"Chapter 4 - Academic Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 4235",title:"Credit for Prior Learning",chapter:"Chapter 4 - Academic Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 4237",title:"Honors Courses and Programs",chapter:"Chapter 4 - Academic Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 4240",title:"Academic Renewal",chapter:"Chapter 4 - Academic Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 5005",title:"Residency Requirements",chapter:"Chapter 5 - Student Services",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 5010",title:"Admissions",chapter:"Chapter 5 - Student Services",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 5011",title:"Admission and Concurrent Enrollment of High School and Other Young Students",chapter:"Chapter 5 - Student Services",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 5012",title:"International Students",chapter:"Chapter 5 - Student Services",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 5020",title:"Nonresident Tuition",chapter:"Chapter 5 - Student Services",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 5030",title:"Student Fees",chapter:"Chapter 5 - Student Services",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 5031",title:"Instructional Materials",chapter:"Chapter 5 - Student Services",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 5035",title:"Withholding Student Diplomas and Registration",chapter:"Chapter 5 - Student Services",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 5050",title:"Disclosure of Student Records",chapter:"Chapter 5 - Student Services",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 5050 (New)",title:"Student Success and Support Program",chapter:"Chapter 5 - Student Services",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 5055",title:"Enrollment Priorities",chapter:"Chapter 5 - Student Services",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 5075",title:"Credit Course Adds, Drops, and Withdrawals",chapter:"Chapter 5 - Student Services",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 5090",title:"Health Services",chapter:"Chapter 5 - Student Services",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 5095",title:"Infectious Disease Control",chapter:"Chapter 5 - Student Services",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 5110",title:"Counseling",chapter:"Chapter 5 - Student Services",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 5120",title:"Transfer Center",chapter:"Chapter 5 - Student Services",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 5130",title:"Financial Aid",chapter:"Chapter 5 - Student Services",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 5140",title:"Disabled Students Programs and Services",chapter:"Chapter 5 - Student Services",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 5300",title:"Student Equity",chapter:"Chapter 5 - Student Services",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 5500",title:"Student Rights and Responsibilities",chapter:"Chapter 5 - Student Services",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 5560",title:"Associated Students",chapter:"Chapter 5 - Student Services",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 5561",title:"Associated Students Elections",chapter:"Chapter 5 - Student Services",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 5562",title:"Associated Students Finance",chapter:"Chapter 5 - Student Services",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 5700",title:"Intercollegiate Athletics: Concussion Management Protocol",chapter:"Chapter 5 - Student Services",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 6100",title:"Delegation of Authority, Business and Fiscal Affairs",chapter:"Chapter 6 - Business and Fiscal Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 6150",title:"Designation of Authorized Signatures",chapter:"Chapter 6 - Business and Fiscal Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 6250",title:"Budget Management",chapter:"Chapter 6 - Business and Fiscal Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 6300",title:"Fiscal Management",chapter:"Chapter 6 - Business and Fiscal Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 6307",title:"Debt Issuance and Management",chapter:"Chapter 6 - Business and Fiscal Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 6320",title:"Investments",chapter:"Chapter 6 - Business and Fiscal Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 6340",title:"Bids and Contracts",chapter:"Chapter 6 - Business and Fiscal Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 6450",title:"Wireless or Cellular Telephone Use",chapter:"Chapter 6 - Business and Fiscal Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 6500",title:"Property Management",chapter:"Chapter 6 - Business and Fiscal Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 6540",title:"Insurance",chapter:"Chapter 6 - Business and Fiscal Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 6600",title:"Capital Construction",chapter:"Chapter 6 - Business and Fiscal Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 6700",title:"Civic Center and Other Facilities",chapter:"Chapter 6 - Business and Fiscal Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 6740",title:"Citizens' Bond Oversight Committee",chapter:"Chapter 6 - Business and Fiscal Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 6750",title:"Parking",chapter:"Chapter 6 - Business and Fiscal Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 6800",title:"Occupational Safety",chapter:"Chapter 6 - Business and Fiscal Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 6870",title:"Police Department",chapter:"Chapter 6 - Business and Fiscal Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 6910",title:"Housing",chapter:"Chapter 6 - Business and Fiscal Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 6510",title:"Guidelines for Administering Environmentally Sustainable Practices",chapter:"Chapter 6 - Business and Fiscal Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 6980",title:"Signage on District Property",chapter:"Chapter 6 - Business and Fiscal Affairs",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 4130",title:"District Hiring Procedures",chapter:"Chapter 7 - Human Resources",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 4157",title:"Definitions and Procedures for Release Time",chapter:"Chapter 7 - Human Resources",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 4670",title:"Procedures for Requesting and Receiving Accommodation(s) under the ADA",chapter:"Chapter 7 - Human Resources",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 7330",title:"Communicable Disease - Employees",chapter:"Chapter 7 - Human Resources",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 7336",title:"Certification of Freedom from Tuberculosis",chapter:"Chapter 7 - Human Resources",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 7337",title:"Fingerprinting of Employees, Volunteers and Student Workers",chapter:"Chapter 7 - Human Resources",type:"Administrative Procedure",adopted:"",lastRevised:""},
{number:"AP 7400",title:"Employee Travel",chapter:"Chapter 7 - Human Resources",type:"Administrative Procedure",adopted:"",lastRevised:""},
];
